spring.application.name=cafeteria

spring.datasource.url=jdbc:mysql://localhost:3306/cafeteria_
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

